### ISSUE TITLE
Pip install not working

### ISSUE THREAD

**Issue by Josef-Friedrich** [9999years/argdown#1]
```
pip3 install argdown
```

```
python3:

>>> import argdown
```

```
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import argdown
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/argdown/__init__.py", line 1, in <module>
    from argdown.argdown import *
  File "/usr/local/lib/python3.6/dist-packages/argdown/argdown.py", line 272
    if os.is_file('.argdown')
                            ^
SyntaxError: invalid syntax
```

**Comment by 9999years** [comment]
hello, yes, i’m not very surprised it’s broken. sorry it took me so long to get back to this!

here’s why, really: it relies on evaluating the whole file. it’s horrible. it’s [a bad idea.](https://eev.ee/blog/2012/03/24/on-principle/) i’ve been thinking about it for a while and i think a solution is to 

1. abandon RST entirely — package long_descriptions can be in markdown now
2. move to a functional interface; require the module have a function called something like `argparser()` that returns the argparse *object* itself, which can be used by `main()` to parse argv or by argdown to create documentation

sound good? i might work on it soon, but time is limited! PRs welcome 😸

**Comment by Josef-Friedrich** [comment]
Your proposals sound really good. Are you aware of this project: [sphinx-argparse](https://github.com/ribozz/sphinx-argparse)? It is a extension for sphinx. Maybe you can reuse code from this project? [Here I tried sphinx-argparse](https://lively-lights.readthedocs.io/en/latest/cli.html). But `sphinx-argparse` lacks the ability to render restructured text files or markdown files directly how your project does or should do.
